name: Publish Packages

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish RentmanSharp
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: RentmanSharp.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          VERSION_REGEX: ^\s*<AssemblyVersion>(.*)<\/AssemblyVersion>$
